import type { FastifyInstance } from 'fastify';
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const field = (key: string) => escape(process.env[key] || `[출시 전 ${key} 입력]`);
export const legalFields = ['LEGAL_OPERATOR','LEGAL_REPRESENTATIVE','LEGAL_ADDRESS','LEGAL_BUSINESS_NUMBER','LEGAL_COMMERCE_NUMBER','SUPPORT_EMAIL','LEGAL_PRIVACY_OFFICER','LEGAL_EFFECTIVE_DATE','LEGAL_PROCESSORS','LEGAL_OVERSEAS_TRANSFER','LEGAL_RETENTION'] as const;
export function registerLegal(app: FastifyInstance) {
  const page = (title: string, content: string) => `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · AI 감지기</title><style>body{margin:0;background:#f3f6fc;color:#17243a;font:16px/1.85 system-ui,sans-serif}main{max-width:800px;margin:40px auto;padding:32px;background:white;border-radius:28px}h1{font-size:32px}h2{margin-top:36px;font-size:21px}a{color:#345dcc}nav{display:flex;gap:20px;flex-wrap:wrap}.notice{padding:18px;background:#edf2ff;border-radius:14px}footer{margin-top:40px;color:#576579} @media(max-width:600px){main{margin:0;padding:24px;border-radius:0}} </style><main><nav><a href="/">AI 감지기</a><a href="/privacy">개인정보처리방침</a><a href="/terms">이용약관</a><a href="/support">고객지원</a></nav><h1>${title}</h1>${legalFields.some(key => !process.env[key]) ? '<p class="notice">검토용 초안입니다. 운영자 정보와 처리업체·국외이전·보유기간을 확정한 뒤 공개해야 합니다.</p>' : ''}${content}<footer>시행일: ${field('LEGAL_EFFECTIVE_DATE')}<br>운영자: ${field('LEGAL_OPERATOR')} · 대표자: ${field('LEGAL_REPRESENTATIVE')}<br>주소: ${field('LEGAL_ADDRESS')}<br>사업자등록번호: ${field('LEGAL_BUSINESS_NUMBER')} · 통신판매업 신고: ${field('LEGAL_COMMERCE_NUMBER')}<br>문의: ${field('SUPPORT_EMAIL')}</footer></main></html>`;
  const mediaProvider = process.env.AI_PROVIDER === 'illuminarty' ? 'Illuminarty' : 'Sightengine';
  const privacy = () => `
  <p>AI 감지기는 분석과 횟수권 제공에 필요한 정보를 아래와 같이 처리합니다.</p>
  <h2>1. 처리 항목과 목적</h2><p>선택한 텍스트, 사진, 짧은 영상 또는 공개 Instagram URL과 미리보기 이미지를 AI 생성 가능성 분석에 사용합니다. 지갑 식별자, 복구키의 해시, 잔여 횟수, Apple 거래 식별자·상품·환불 상태는 결제 검증, 중복 충전 방지, 복구와 분쟁 처리에 사용합니다. 결제 수단 정보는 Apple이 처리하며 앱 서버는 카드번호를 수집하지 않습니다.</p>
  <h2>2. 저장 위치와 보유기간</h2><p>텍스트·이미지 원본은 서버 DB에 저장하지 않고 요청 처리 메모리에서 사용합니다. 영상은 길이 확인을 위한 임시 파일로 생성한 뒤 처리 직후 삭제합니다. 결과·미리보기 주소는 네트워크 재시도를 위해 서버에 24시간 보유 후 1분 주기의 정리 작업에서 삭제합니다. 중복 과금 방지용 요청 식별자·해시·상태와 지갑·거래 기록은 횟수권 제공 및 법적 의무에 필요한 기간 보유합니다. 구체적 보유기간 및 법적 근거: ${field('LEGAL_RETENTION')}</p><p>분석 이력과 원문 링크는 기기에 저장되며 앱의 기록 화면에서 삭제할 수 있습니다. 지갑 복구키는 기기의 Keychain에 저장됩니다. 서버 요청 본문과 인증키는 로그에 기록하지 않도록 설정했습니다. 호스팅·프록시 로그의 항목과 보유기간도 위 보유기간 설정에 포함됩니다.</p>
  <h2>3. 외부 처리업체 및 국외이전</h2><p>텍스트는 GPTZero API, 이미지 및 지원 영상은 ${mediaProvider} API로 전송해 분석합니다. Instagram 링크는 공개 미리보기를 불러오는 데 사용합니다. Apple은 인앱결제 처리를 담당합니다. 업체명, 위탁 업무와 호스팅 제공자: ${field('LEGAL_PROCESSORS')}</p><p>국외이전 받는 자와 연락처, 이전 국가, 항목, 목적, 시기·방법, 보유기간, 법적 근거 및 거부 방법: ${field('LEGAL_OVERSEAS_TRANSFER')}</p><p>이용자는 분석 화면에서 외부 전송 안내를 확인하고 분석을 선택할 수 있습니다. 전송을 거부하면 해당 분석은 이용할 수 없습니다. 업체의 보관·학습 이용 여부는 계약과 각 업체 정책에 따르며, 운영자가 임의로 즉시 삭제를 보장하지 않습니다.</p>
  <h2>4. 권리 행사와 삭제</h2><p>정보 열람, 정정, 삭제, 처리정지 및 동의 철회를 고객지원에 요청할 수 있습니다. 지갑 ID와 필요한 최소 정보로 본인을 확인하며 복구키 전체는 보내지 마세요. 법적 보관 의무가 있으면 해당 정보의 삭제가 제한될 수 있고 사유를 안내합니다. 기기 이력 삭제는 서버의 거래 기록 삭제와 별개입니다.</p>
  <h2>5. 안전조치 및 파기</h2><p>전송 구간 암호화, 접근 권한 제한, 인증키 해시화, 원본 저장 최소화를 적용합니다. 보유 목적이 끝난 전자 기록은 복구하기 어려운 방법으로 삭제합니다. 법정 보관 정보는 이용 목적을 제한합니다. 백업과 로그도 확정된 보유기간에 따라 삭제합니다.</p>
  <h2>6. 아동 및 민감정보</h2><p>서비스는 만 14세 이상을 대상으로 합니다. 타인의 개인정보나 민감정보를 권한 없이 제출하지 마세요. 14세 미만 이용 사실을 알게 된 경우 필요한 보호 및 삭제 조치를 진행합니다.</p>
  <h2>7. 자동 수집과 변경 안내</h2><p>현재 앱에 광고 추적 SDK나 광고 식별자를 사용하지 않습니다. 처리 내용이 변경되면 앱 또는 이 페이지에서 시행일과 변경 내용을 안내하며 추가 동의가 필요한 경우 별도로 받습니다.</p>
  <h2>8. 개인정보 보호책임자</h2><p>${field('LEGAL_PRIVACY_OFFICER')} · ${field('SUPPORT_EMAIL')}</p><p>권리 침해 관련 상담은 개인정보침해신고센터(118), 개인정보분쟁조정위원회(1833-6972)를 통해 요청할 수 있습니다.</p>`;
  const terms = () => `
  <h2>1. 서비스 및 이용 조건</h2><p>AI 감지기는 외부 AI 탐지 API를 이용해 콘텐츠의 AI 생성 가능성을 추정하는 서비스입니다. 만 14세 이상 이용자가 본 약관과 개인정보 처리 안내를 확인하고 이용할 수 있습니다. 입력 콘텐츠에 필요한 이용·전송 권한은 이용자가 확보해야 합니다.</p>
  <h2>2. 분석 범위와 한계</h2><p>텍스트 250~10,000자, 지원 이미지 파일, 10초·10MB 이하 MP4/MOV 영상을 지원합니다. URL 분석은 공개 Instagram의 미리보기 이미지에 한정되며 영상 전체나 게시물의 모든 사진을 분석하지 않습니다. 업로드 영상은 샘플 프레임 점수의 평균을 표시합니다. 텍스트는 문서 전체가 AI로 생성되었을 가능성을 표시합니다. 언어·길이·압축·편집에 따라 오류가 발생할 수 있으며 결과는 저작권, 부정행위, 사실 여부 또는 개인의 신뢰성을 확정하는 증거가 아닙니다.</p>
  <h2>3. 횟수권 및 결제</h2><p>6회·20회·50회 횟수권을 Apple 인앱결제로 구매합니다. 구독이나 자동 갱신은 없습니다. 가격·통화·세금 포함 여부는 구매 화면과 Apple 최종 확인 화면에 표시되는 내용을 따릅니다. 한 번의 정상 완료된 분석에 1회를 사용합니다. 실패한 분석은 차감하지 않으며 같은 요청의 재전송으로 중복 차감하지 않습니다. 이용자가 새 분석을 요청하면 같은 콘텐츠라도 새로 1회를 사용합니다. 구매한 미사용 횟수에는 유효기간을 두지 않습니다.</p>
  <h2>4. 지갑과 복구</h2><p>잔여 횟수는 서버 지갑에 기록됩니다. 복구키를 안전하게 보관하면 다른 기기나 재설치 후 같은 지갑을 연결할 수 있습니다. 소모성 구매는 Apple의 일반 구매 복원만으로 복구되지 않을 수 있습니다. 미지급 구매는 앱에서 재확인할 수 있습니다. 키 분실 시 고객지원에 Apple 거래 내역을 제공하여 확인을 요청할 수 있으나 증명이 불가능한 경우 복구가 제한됩니다. 복구키를 타인에게 공유하지 마세요.</p>
  <h2>5. 청약철회·환불·오지급</h2><p>환불은 Apple의 문제 신고 페이지 또는 고객지원을 통해 요청할 수 있으며 적용 법령과 Apple의 심사 절차에 따릅니다. 이용자의 법정 청약철회·환불 권리를 배제하지 않습니다. 공급 개시 후의 디지털 콘텐츠에는 법정 예외 요건이 충족되는 범위에서 철회가 제한될 수 있습니다. 환불된 구매에 해당하는 횟수는 회수하며 이미 사용한 경우 지갑 잔액이 음수가 될 수 있습니다. 중복 청구·미지급·오류는 고객지원으로 알려주세요.</p>
  <h2>6. 이용 제한 및 서비스 변경</h2><p>결제 위조, 자동화 남용, 타인 권리 침해 등 위법·부정 이용은 제한할 수 있으며 사유 및 이의 제기 방법을 안내합니다. 중요한 가격·기능·약관 변경은 사전에 알립니다. 변경 가격은 새 구매에 적용됩니다. 서비스 종료 시 잔여 횟수 처리와 환불 방안을 사전에 안내하며 법령상 의무를 이행합니다.</p>
  <h2>7. 책임과 분쟁</h2><p>운영자는 안정적 서비스 제공을 위해 노력하며 고의·과실 및 강행법규에 따른 책임을 부담합니다. 외부 API 장애 시 분석 실패로 처리하고 횟수를 돌려드립니다. 본 약관은 대한민국 법령을 기준으로 작성되었으며 소비자에게 적용되는 강행규정과 법정 관할을 제한하지 않습니다. 분쟁은 고객지원 및 관계 법령의 분쟁 해결 절차를 통해 처리합니다.</p>`;
  app.get('/privacy', async (_,reply) => reply.type('text/html; charset=utf-8').send(page('개인정보처리방침',privacy())));
  app.get('/terms', async (_,reply) => reply.type('text/html; charset=utf-8').send(page('이용약관',terms())));
  app.get('/support', async (_,reply) => reply.type('text/html; charset=utf-8').send(page('고객지원',`<p>구매·복구·개인정보 문의: ${field('SUPPORT_EMAIL')}</p><p>지갑 ID와 Apple 거래번호를 함께 알려주세요. 복구키는 보내지 마세요.</p><p><a href="https://reportaproblem.apple.com/">Apple 환불 요청</a></p>`)));
  app.get('/', async (_,reply) => reply.type('text/html; charset=utf-8').send(page('필요한 만큼, 합리적인 AI 분석',`<p>외부 AI 탐지 API로 텍스트·이미지·짧은 영상을 분석하세요.</p><p>매달 내는 구독료 없이 필요한 횟수만 구매합니다. 실제 판매가격과 회당 가격은 앱에서 확인하세요.</p><p>분석 결과는 참고용 추정치입니다.</p>`)));
}
